### ISSUE TITLE
ordering the components

### ISSUE THREAD

**Issue by mikeshams** [nireehasharma/Capstone-Project_G3#1]
what points did you consider when choosing a company to order your components from?

**Comment by SumanMosam** [comment]
First of all, we tried to get components as quickly as possible and we also considered the quality of the components. So we bought some items which are available on Amazon.ca we choose it because as it's reliable and fast delivering. Next, we choose the Digi key, Elmwood and Adafruit websites even though the shipping and delivery time is a little long but we believed in their products. And the cost, Customer rating, Return policy and Protection & Damage policy for the components while shipping is also considered when we choose those websites.
