### ISSUE TITLE
Cloud Storage Management

### ISSUE THREAD

**Issue by mikeshams** [nireehasharma/Capstone-Project_G3#6]
Add a feature to record your prescription advice to the patients (date and time)

**Comment by nireehasharma** [comment]
Greetings of the day sir,

For my 2nd individual meeting, I've been asked to include a particular date along with time in my HTML page, So, for our project, we basically have a rotating board that has 4 quadrants on which the medicines will be placed by a supervisor of the medication. So, we have not thought about including a date since ours is a small-scale project, doing so will complicate our entire project the way it's going now. I've had a meeting with my other group mates - Nishitha, Satya, Suman and they felt the same.

could you please suggest.

Thanks and Regards,
Lakshmi
